version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=SocialSecInstDB;User Id=sa;Password=loj123.123;TrustServerCertificate=True;MultipleActiveResultSets=true;