// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialSecurityInstitution.DataAccessLayer.ConcreteDatabase;

#nullable disable

namespace SocialSecurityInstitution.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240308084913_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtanmaNedeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AtanmaNedeni")
                        .IsUnique();

                    b.ToTable("AtanmaNedenleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankoIslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankoGrup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankoIslemAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BankoIslemAktiflik")
                        .HasColumnType("int");

                    b.Property<int>("BankoIslemSira")
                        .HasColumnType("int");

                    b.Property<int>("BankoUstIslemId")
                        .HasColumnType("int");

                    b.Property<string>("DiffLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankoIslemAdı")
                        .IsUnique();

                    b.ToTable("BankoIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankoAktiflik")
                        .HasColumnType("int");

                    b.Property<int>("BankoNo")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId", "BankoNo", "BankoAktiflik")
                        .IsUnique();

                    b.ToTable("Bankolar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankolarKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonellerTcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BankoId")
                        .IsUnique();

                    b.HasIndex("PersonellerTcKimlikNo");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("BankolarKullanici");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmanAktiflik")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanAdi")
                        .IsUnique();

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HizmetBinasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HizmetBinalari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Iller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IlAdi")
                        .IsUnique();

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KanalAltIslemAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KanalIslemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KanalIslemId");

                    b.ToTable("KanalAltIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaslangicNumara")
                        .HasColumnType("int");

                    b.Property<int>("BitisNumara")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KanalIslemAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KanalIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalPersonelleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KanalAltIslemId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelKanalAltIslemAktiflik")
                        .HasColumnType("int");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KanalAltIslemId");

                    b.HasIndex("TcKimlikNo");

                    b.ToTable("KanalPersonelleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.LoginLogoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LogoutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo");

                    b.ToTable("LoginLogoutLog");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PdksCihazlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Aktiflik")
                        .HasColumnType("int");

                    b.Property<string>("CihazIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CihazPort")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("IslemBasari")
                        .HasColumnType("int");

                    b.Property<string>("IslemDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslemSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KontrolBasari")
                        .HasColumnType("int");

                    b.Property<string>("KontrolDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KontrolSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KontrolZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("PdksCihazlar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelCocuklari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CocukAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CocukDogumTarihi")
                        .HasColumnType("date");

                    b.Property<int>("OgrenimDurumu")
                        .HasColumnType("int");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo");

                    b.ToTable("PersonelCocuklari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelYetkileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.Property<string>("YetkiTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo");

                    b.HasIndex("YetkiId");

                    b.ToTable("PersonelYetkileri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtanmaNedeniId")
                        .HasColumnType("int");

                    b.Property<string>("BitirdigiBolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BitirdigiOkul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bransi")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CezaBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CocukBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dahili")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EgitimBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmekliSicilNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngelBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininIsAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininIsDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EsininIsIlId")
                        .HasColumnType("int");

                    b.Property<int?>("EsininIsIlceId")
                        .HasColumnType("int");

                    b.Property<string>("EsininIsSemt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininUnvani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizmetBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.Property<int?>("IlId")
                        .HasColumnType("int");

                    b.Property<int?>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("ImzaYetkileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KanGrubu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedeniDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenimDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenimSuresi")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelAktiflikDurum")
                        .HasColumnType("int");

                    b.Property<string>("PersonelTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SehitYakinligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SendikaId")
                        .HasColumnType("int");

                    b.Property<int>("ServisId")
                        .HasColumnType("int");

                    b.Property<int>("SicilNo")
                        .HasColumnType("int");

                    b.Property<int>("Tabldot")
                        .HasColumnType("int");

                    b.Property<int>("UlasimServis1")
                        .HasColumnType("int");

                    b.Property<int>("UlasimServis2")
                        .HasColumnType("int");

                    b.Property<int>("UnvanId")
                        .HasColumnType("int");

                    b.Property<string>("Uzmanlik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TcKimlikNo");

                    b.HasIndex("AtanmaNedeniId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("EsininIsIlId");

                    b.HasIndex("EsininIsIlceId");

                    b.HasIndex("HizmetBinasiId");

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.HasIndex("SendikaId");

                    b.HasIndex("ServisId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("UnvanId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SendikaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SendikaAdi")
                        .IsUnique();

                    b.ToTable("Sendikalar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Servisler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServisAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServisAktiflik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServisAdi")
                        .IsUnique();

                    b.ToTable("Servisler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnvanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnvanAktiflik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnvanAdi")
                        .IsUnique();

                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UstYetkiId")
                        .HasColumnType("int");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YetkiAktiflik")
                        .HasColumnType("int");

                    b.Property<string>("YetkiTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("YetkiAdi", "YetkiAktiflik")
                        .IsUnique();

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany("Bankolar_")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankolarKullanici", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", "Banko")
                        .WithMany("BankolarKullanici_")
                        .HasForeignKey("BankoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", null)
                        .WithMany("BankolarKullanici_")
                        .HasForeignKey("PersonellerTcKimlikNo");

                    b.Navigation("Banko");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "Il")
                        .WithMany("Ilceler_")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", "KanalIslem")
                        .WithMany("KanalAltIslemleri_")
                        .HasForeignKey("KanalIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanalIslem");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalPersonelleri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", "KanalAltIslem")
                        .WithMany()
                        .HasForeignKey("KanalAltIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany("KanalPersonelleri_")
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanalAltIslem");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.LoginLogoutLog", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany("LoginLogoutLog_")
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PdksCihazlar", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelCocuklari", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany("PersonelCocuklari_")
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelYetkileri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany("PersonelYetkileri_")
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", "Yetki")
                        .WithMany("PersonelYetkileri_")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", "AtanmaNedeni")
                        .WithMany("Personeller_")
                        .HasForeignKey("AtanmaNedeniId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany("Personeller_")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "EsininIsIl")
                        .WithMany()
                        .HasForeignKey("EsininIsIlId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", "EsininIsIlce")
                        .WithMany()
                        .HasForeignKey("EsininIsIlceId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinasi")
                        .WithMany("Personeller_")
                        .HasForeignKey("HizmetBinasiId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "Il")
                        .WithMany()
                        .HasForeignKey("IlId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", "Sendika")
                        .WithMany("Personeller_")
                        .HasForeignKey("SendikaId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Servisler", "Servis")
                        .WithMany()
                        .HasForeignKey("ServisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", "Unvan")
                        .WithMany("Personeller_")
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtanmaNedeni");

                    b.Navigation("Departman");

                    b.Navigation("EsininIsIl");

                    b.Navigation("EsininIsIlce");

                    b.Navigation("HizmetBinasi");

                    b.Navigation("Il");

                    b.Navigation("Ilce");

                    b.Navigation("Sendika");

                    b.Navigation("Servis");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.Navigation("BankolarKullanici_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", b =>
                {
                    b.Navigation("Bankolar_");

                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Iller", b =>
                {
                    b.Navigation("Ilceler_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", b =>
                {
                    b.Navigation("KanalAltIslemleri_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.Navigation("BankolarKullanici_");

                    b.Navigation("KanalPersonelleri_");

                    b.Navigation("LoginLogoutLog_");

                    b.Navigation("PersonelCocuklari_");

                    b.Navigation("PersonelYetkileri_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", b =>
                {
                    b.Navigation("PersonelYetkileri_");
                });
#pragma warning restore 612, 618
        }
    }
}
