// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialSecurityInstitution.DataAccessLayer.ConcreteDatabase;

#nullable disable

namespace SocialSecurityInstitution.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240812113103_mig_4")]
    partial class mig_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Siralar", b =>
                {
                    b.Property<int>("SiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiraId"));

                    b.Property<int>("BeklemeDurum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IslemBaslamaZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IslemBitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KanalAltIslemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiraAlisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SiraAlisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SiraId");

                    b.HasIndex("KanalAltIslemId");

                    b.HasIndex("TcKimlikNo");

                    b.HasIndex("SiraNo", "SiraAlisTarihi")
                        .IsUnique();

                    b.ToTable("Siralar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", b =>
                {
                    b.Property<int>("AtanmaNedeniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtanmaNedeniId"));

                    b.Property<string>("AtanmaNedeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("AtanmaNedeniId");

                    b.HasIndex("AtanmaNedeni")
                        .IsUnique();

                    b.ToTable("AtanmaNedenleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankoIslemleri", b =>
                {
                    b.Property<int>("BankoIslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankoIslemId"));

                    b.Property<string>("BankoGrup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankoIslemAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BankoIslemAktiflik")
                        .HasColumnType("int");

                    b.Property<int>("BankoIslemSira")
                        .HasColumnType("int");

                    b.Property<int>("BankoUstIslemId")
                        .HasColumnType("int");

                    b.Property<string>("DiffLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("BankoIslemId");

                    b.HasIndex("BankoIslemAdı")
                        .IsUnique();

                    b.ToTable("BankoIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.Property<int>("BankoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankoId"));

                    b.Property<int>("BankoAktiflik")
                        .HasColumnType("int");

                    b.Property<int>("BankoNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.HasKey("BankoId");

                    b.HasIndex("HizmetBinasiId", "BankoNo", "BankoAktiflik")
                        .IsUnique();

                    b.ToTable("Bankolar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankolarKullanici", b =>
                {
                    b.Property<int>("BankoKullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankoKullaniciId"));

                    b.Property<int>("BankoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonellerTcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BankoKullaniciId");

                    b.HasIndex("BankoId")
                        .IsUnique();

                    b.HasIndex("PersonellerTcKimlikNo");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("BankolarKullanici");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.DatabaseLog", b =>
                {
                    b.Property<int>("DatabaseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseLogId"));

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AfterData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonellerTcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatabaseLogId");

                    b.HasIndex("PersonellerTcKimlikNo");

                    b.ToTable("DatabaseLog");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Kanallar", b =>
                {
                    b.Property<int>("KanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KanalAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KanalId");

                    b.HasIndex("KanalAdi")
                        .IsUnique();

                    b.ToTable("Kanallar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KanallarAlt", b =>
                {
                    b.Property<int>("KanalAltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalAltId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KanalAltAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KanallarKanalId")
                        .HasColumnType("int");

                    b.Property<int?>("KioskIslemGruplariKioskIslemGrupId")
                        .HasColumnType("int");

                    b.HasKey("KanalAltId");

                    b.HasIndex("KanalAltAdi")
                        .IsUnique();

                    b.HasIndex("KanallarKanalId");

                    b.HasIndex("KioskIslemGruplariKioskIslemGrupId");

                    b.ToTable("KanallarAlt");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskGruplari", b =>
                {
                    b.Property<int>("KioskGrupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KioskGrupId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KioskGrupAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KioskGrupId");

                    b.HasIndex("KioskGrupAdi")
                        .IsUnique();

                    b.ToTable("KioskGruplari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskIslemGruplari", b =>
                {
                    b.Property<int>("KioskIslemGrupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KioskIslemGrupId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.Property<int>("KioskGrupId")
                        .HasColumnType("int");

                    b.Property<int>("KioskIslemGrupAktiflik")
                        .HasColumnType("int");

                    b.Property<int>("KioskIslemGrupSira")
                        .HasColumnType("int");

                    b.HasKey("KioskIslemGrupId");

                    b.HasIndex("HizmetBinasiId", "KioskIslemGrupSira")
                        .IsUnique();

                    b.HasIndex("KioskGrupId", "HizmetBinasiId")
                        .IsUnique();

                    b.ToTable("KioskIslemGruplari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulController", b =>
                {
                    b.Property<int>("ControllerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ControllerId"));

                    b.Property<string>("ControllerAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModulId")
                        .HasColumnType("int");

                    b.HasKey("ControllerId");

                    b.HasIndex("ModulId");

                    b.ToTable("ModulController");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulControllerIslemler", b =>
                {
                    b.Property<int>("ControllerIslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ControllerIslemId"));

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<string>("ControllerIslemAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ControllerIslemId");

                    b.HasIndex("ControllerId");

                    b.ToTable("ModulControllerIslemler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Moduller", b =>
                {
                    b.Property<int>("ModulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModulId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModulId");

                    b.ToTable("Modul");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModullerAlt", b =>
                {
                    b.Property<int>("ModulAltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModulAltId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModulAltAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModulId")
                        .HasColumnType("int");

                    b.HasKey("ModulAltId");

                    b.HasIndex("ModulId");

                    b.ToTable("ModullerAlt");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.PersonelYetkileri", b =>
                {
                    b.Property<int>("PersonelYetkiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelYetkiId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YetkiControllerIslemId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTipleri")
                        .HasColumnType("int");

                    b.HasKey("PersonelYetkiId");

                    b.HasIndex("TcKimlikNo");

                    b.HasIndex("YetkiControllerIslemId");

                    b.ToTable("PersonelYetkileri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", b =>
                {
                    b.Property<int>("DepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanId"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmanAktiflik")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmanId");

                    b.HasIndex("DepartmanAdi")
                        .IsUnique();

                    b.ToTable("Departmanlar");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", b =>
                {
                    b.Property<int>("HizmetBinasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetBinasiId"));

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmanlarDepartmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HizmetBinasiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HizmetBinasiAktiflik")
                        .HasColumnType("int");

                    b.HasKey("HizmetBinasiId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("DepartmanlarDepartmanId");

                    b.ToTable("HizmetBinalari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HubConnection", b =>
                {
                    b.Property<int>("HubConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HubConnectionId"));

                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HubConnectionId");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique()
                        .HasFilter("[TcKimlikNo] IS NOT NULL");

                    b.ToTable("HubConnection");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceId"));

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlceId");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Iller", b =>
                {
                    b.Property<int>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlId"));

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IlId");

                    b.HasIndex("IlAdi")
                        .IsUnique();

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", b =>
                {
                    b.Property<int>("KanalAltIslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalAltIslemId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.Property<int>("KanalAltId")
                        .HasColumnType("int");

                    b.Property<int>("KanalAltIslemAktiflik")
                        .HasColumnType("int");

                    b.Property<int?>("KanalIslemId")
                        .HasColumnType("int");

                    b.Property<int?>("KioskIslemGrupId")
                        .HasColumnType("int");

                    b.HasKey("KanalAltIslemId");

                    b.HasIndex("KanalAltId");

                    b.HasIndex("KanalIslemId");

                    b.HasIndex("KioskIslemGrupId");

                    b.HasIndex("HizmetBinasiId", "KanalAltId")
                        .IsUnique();

                    b.ToTable("KanalAltIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", b =>
                {
                    b.Property<int>("KanalIslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalIslemId"));

                    b.Property<int>("BaslangicNumara")
                        .HasColumnType("int");

                    b.Property<int>("BitisNumara")
                        .HasColumnType("int");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.Property<int>("KanalId")
                        .HasColumnType("int");

                    b.Property<int>("KanalIslemAktiflik")
                        .HasColumnType("int");

                    b.HasKey("KanalIslemId");

                    b.HasIndex("KanalId");

                    b.HasIndex("HizmetBinasiId", "KanalId")
                        .IsUnique();

                    b.ToTable("KanalIslemleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalPersonelleri", b =>
                {
                    b.Property<int>("KanalPersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KanalPersonelId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KanalAltIslemId")
                        .HasColumnType("int");

                    b.Property<int>("KanalAltIslemPersonelAktiflik")
                        .HasColumnType("int");

                    b.Property<string>("PersonellerTcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Uzmanlik")
                        .HasColumnType("int");

                    b.HasKey("KanalPersonelId");

                    b.HasIndex("PersonellerTcKimlikNo");

                    b.HasIndex("TcKimlikNo");

                    b.HasIndex("KanalAltIslemId", "TcKimlikNo")
                        .IsUnique();

                    b.ToTable("KanalPersonelleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.LoginLogoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LoginTime");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LogoutTime");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SessionID");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TcKimlikNo");

                    b.HasKey("Id");

                    b.ToTable("LoginLogoutLog");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PdksCihazlar", b =>
                {
                    b.Property<int>("PdksCihazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdksCihazId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Aktiflik")
                        .HasColumnType("int");

                    b.Property<string>("CihazIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CihazPort")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("IslemBasari")
                        .HasColumnType("int");

                    b.Property<string>("IslemDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslemSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KontrolBasari")
                        .HasColumnType("int");

                    b.Property<string>("KontrolDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KontrolSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KontrolZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("PdksCihazId");

                    b.HasIndex("DepartmanId");

                    b.ToTable("PdksCihazlar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelCocuklari", b =>
                {
                    b.Property<int>("PersonelCocukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelCocukId"));

                    b.Property<string>("CocukAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CocukDogumTarihi")
                        .HasColumnType("date");

                    b.Property<string>("OgrenimDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelTcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelCocukId");

                    b.ToTable("PersonelCocuklari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelYetkileriii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonelTcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.Property<int>("YetkiTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YetkiId");

                    b.ToTable("PersonelYetkileriii");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtanmaNedeniId")
                        .HasColumnType("int");

                    b.Property<string>("BitirdigiBolum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BitirdigiOkul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bransi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTelefonu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CezaBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dahili")
                        .HasColumnType("int");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EgitimBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmekliSicilNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngelBilgileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininIsAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininIsDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EsininIsIlId")
                        .HasColumnType("int");

                    b.Property<int>("EsininIsIlceId")
                        .HasColumnType("int");

                    b.Property<string>("EsininIsSemt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsininUnvani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizmetBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HizmetBinasiId")
                        .HasColumnType("int");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("ImzaYetkileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KanGrubu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KartGonderimIslemBasari")
                        .HasColumnType("int");

                    b.Property<int>("KartNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KartNoAktiflikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KartNoDuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KartNoGonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedeniDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenimDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenimSuresi")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonelAktiflikDurum")
                        .HasColumnType("int");

                    b.Property<int>("PersonelKayitNo")
                        .HasColumnType("int");

                    b.Property<string>("PersonelTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SehitYakinligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SendikaId")
                        .HasColumnType("int");

                    b.Property<int>("ServisId")
                        .HasColumnType("int");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SicilNo")
                        .HasColumnType("int");

                    b.Property<int>("Tabldot")
                        .HasColumnType("int");

                    b.Property<int>("UlasimServis1")
                        .HasColumnType("int");

                    b.Property<int>("UlasimServis2")
                        .HasColumnType("int");

                    b.Property<int>("UnvanId")
                        .HasColumnType("int");

                    b.Property<string>("Uzmanlik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TcKimlikNo");

                    b.HasIndex("AtanmaNedeniId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("EsininIsIlId");

                    b.HasIndex("EsininIsIlceId");

                    b.HasIndex("HizmetBinasiId");

                    b.HasIndex("IlId");

                    b.HasIndex("IlceId");

                    b.HasIndex("SendikaId");

                    b.HasIndex("ServisId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("UnvanId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", b =>
                {
                    b.Property<int>("SendikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SendikaId"));

                    b.Property<string>("SendikaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SendikaId");

                    b.HasIndex("SendikaAdi")
                        .IsUnique();

                    b.ToTable("Sendikalar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Servisler", b =>
                {
                    b.Property<int>("ServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServisId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServisAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServisAktiflik")
                        .HasColumnType("int");

                    b.HasKey("ServisId");

                    b.HasIndex("ServisAdi")
                        .IsUnique();

                    b.ToTable("Servisler");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", b =>
                {
                    b.Property<int>("UnvanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanId"));

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnvanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnvanAktiflik")
                        .HasColumnType("int");

                    b.HasKey("UnvanId");

                    b.HasIndex("UnvanAdi")
                        .IsUnique();

                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", b =>
                {
                    b.Property<int>("YetkiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkiId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UstYetkiId")
                        .HasColumnType("int");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YetkiAktiflik")
                        .HasColumnType("int");

                    b.Property<string>("YetkiTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiId");

                    b.HasIndex("YetkiAdi", "YetkiAktiflik")
                        .IsUnique();

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("Siralar", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", "KanalAltIslem")
                        .WithMany()
                        .HasForeignKey("KanalAltIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personeller")
                        .WithMany()
                        .HasForeignKey("TcKimlikNo");

                    b.Navigation("KanalAltIslem");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinalari")
                        .WithMany("Bankolar")
                        .HasForeignKey("HizmetBinasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HizmetBinalari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.BankolarKullanici", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", "Bankolar")
                        .WithMany("BankolarKullanici")
                        .HasForeignKey("BankoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", null)
                        .WithMany("BankolarKullanici")
                        .HasForeignKey("PersonellerTcKimlikNo");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany()
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bankolar");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.DatabaseLog", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", null)
                        .WithMany("DatabaseLog")
                        .HasForeignKey("PersonellerTcKimlikNo");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KanallarAlt", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Kanallar", null)
                        .WithMany("KanallarAlt_")
                        .HasForeignKey("KanallarKanalId");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskIslemGruplari", null)
                        .WithMany("KanallarAlt_")
                        .HasForeignKey("KioskIslemGruplariKioskIslemGrupId");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskIslemGruplari", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinalari")
                        .WithMany()
                        .HasForeignKey("HizmetBinasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskGruplari", "KioskGruplari")
                        .WithMany("KioskIslemGruplari_")
                        .HasForeignKey("KioskGrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HizmetBinalari");

                    b.Navigation("KioskGruplari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulController", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Moduller", "Modul")
                        .WithMany("Controller")
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modul");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulControllerIslemler", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulController", "Controller")
                        .WithMany("ControllerIslem")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModullerAlt", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Moduller", "Modul")
                        .WithMany("ModullerAlt")
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modul");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.PersonelYetkileri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personeller")
                        .WithMany()
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulControllerIslemler", "Yetki")
                        .WithMany("Yetki")
                        .HasForeignKey("YetkiControllerIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personeller");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", null)
                        .WithMany("HizmetBinalari")
                        .HasForeignKey("DepartmanlarDepartmanId");

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "Il")
                        .WithMany("Ilceler_")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinalari")
                        .WithMany()
                        .HasForeignKey("HizmetBinasiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KanallarAlt", "KanallarAlt")
                        .WithMany("KanalAltIslemleri_")
                        .HasForeignKey("KanalAltId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", "KanalIslem")
                        .WithMany("KanalAltIslemleri_")
                        .HasForeignKey("KanalIslemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskIslemGruplari", "KioskIslemGruplari")
                        .WithMany()
                        .HasForeignKey("KioskIslemGrupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HizmetBinalari");

                    b.Navigation("KanalIslem");

                    b.Navigation("KanallarAlt");

                    b.Navigation("KioskIslemGruplari");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinalari")
                        .WithMany()
                        .HasForeignKey("HizmetBinasiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Kanallar", "Kanallar")
                        .WithMany("KanalIslemleri_")
                        .HasForeignKey("KanalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HizmetBinalari");

                    b.Navigation("Kanallar");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalPersonelleri", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.KanalAltIslemleri", "KanalAltIslem")
                        .WithMany()
                        .HasForeignKey("KanalAltIslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", null)
                        .WithMany("KanalPersonelleri")
                        .HasForeignKey("PersonellerTcKimlikNo");

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Personeller", "Personel")
                        .WithMany()
                        .HasForeignKey("TcKimlikNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KanalAltIslem");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PdksCihazlar", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.PersonelYetkileriii", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", "Yetki")
                        .WithMany("PersonelYetkileri_")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", "AtanmaNedeni")
                        .WithMany("Personeller_")
                        .HasForeignKey("AtanmaNedeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", "Departman")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "EsininIsIl")
                        .WithMany()
                        .HasForeignKey("EsininIsIlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", "EsininIsIlce")
                        .WithMany()
                        .HasForeignKey("EsininIsIlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", "HizmetBinasi")
                        .WithMany("Personeller")
                        .HasForeignKey("HizmetBinasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Iller", "Il")
                        .WithMany()
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Ilceler", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", "Sendika")
                        .WithMany("Personeller_")
                        .HasForeignKey("SendikaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Servisler", "Servis")
                        .WithMany()
                        .HasForeignKey("ServisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", "Unvan")
                        .WithMany("Personeller_")
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtanmaNedeni");

                    b.Navigation("Departman");

                    b.Navigation("EsininIsIl");

                    b.Navigation("EsininIsIlce");

                    b.Navigation("HizmetBinasi");

                    b.Navigation("Il");

                    b.Navigation("Ilce");

                    b.Navigation("Sendika");

                    b.Navigation("Servis");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.AtanmaNedenleri", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Bankolar", b =>
                {
                    b.Navigation("BankolarKullanici");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Kanallar", b =>
                {
                    b.Navigation("KanalIslemleri_");

                    b.Navigation("KanallarAlt_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KanallarAlt", b =>
                {
                    b.Navigation("KanalAltIslemleri_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskGruplari", b =>
                {
                    b.Navigation("KioskIslemGruplari_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.KioskIslemGruplari", b =>
                {
                    b.Navigation("KanallarAlt_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulController", b =>
                {
                    b.Navigation("ControllerIslem");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.ModulControllerIslemler", b =>
                {
                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.DataBaseEntities.Moduller", b =>
                {
                    b.Navigation("Controller");

                    b.Navigation("ModullerAlt");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Departmanlar", b =>
                {
                    b.Navigation("HizmetBinalari");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.HizmetBinalari", b =>
                {
                    b.Navigation("Bankolar");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Iller", b =>
                {
                    b.Navigation("Ilceler_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.KanalIslemleri", b =>
                {
                    b.Navigation("KanalAltIslemleri_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Personeller", b =>
                {
                    b.Navigation("BankolarKullanici");

                    b.Navigation("DatabaseLog");

                    b.Navigation("KanalPersonelleri");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Sendikalar", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Unvanlar", b =>
                {
                    b.Navigation("Personeller_");
                });

            modelBuilder.Entity("SocialSecurityInstitution.BusinessObjectLayer.Yetkiler", b =>
                {
                    b.Navigation("PersonelYetkileri_");
                });
#pragma warning restore 612, 618
        }
    }
}
